language: java

jdk: openjdk11

env:
  global:
    - MAVEN_OPTS="-Xmx7g"
  matrix:
    - TEST=RunBerlinScenarioSmallTests
    - TEST=RunBerlinScenarioTest
    - TEST=AbfallUtilsTest
    - TEST=OpenBerlinIntermodalPtDrtRouterAnalysisModeIdentifierTest
    - TEST=OpenBerlinIntermodalPtDrtRouterModeIdentifierTest
    - TEST=RunBerlinScenarioSingleTripStrategiesTest
    - TEST=RunDrtOpenBerlinScenarioTest
    - TEST=RunDrtOpenBerlinScenarioWithDrtSpeedUpTest
    # - TEST=RunBerlinScenarioIT#test10pctUntilIteration1 # does not fit into travis.  kai, aug'18
    # - TEST=RunBerlinScenarioIT#test1pctManyIterations # does probably not fit into travis (not tested).  kai, aug'18
script:
  - mvn -Dtest=${TEST} test --batch-mode -Dmatsim.preferLocalDtds=true -Dmaven.javadoc.skip -e
